name: secure_counter
description: Example App for Amazon Cognito Identity SDK
  for Dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^1.0.3"
  amazon_cognito_identity_dart:
    git:
      url: https://github.com/stef0296/amazon-cognito-identity-dart
  shared_preferences: "^2.0.6"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
